-- CreateEnum
CREATE TYPE "DispatchBatchStatus" AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'DISPATCHED', 'CANCELLED');

-- CreateTable
CREATE TABLE "driver_zones" (
    "id" TEXT NOT NULL,
    "driverId" TEXT NOT NULL,
    "zone" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "driver_zones_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dispatch_batches" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "dispatchDate" DATE NOT NULL,
    "status" "DispatchBatchStatus" NOT NULL DEFAULT 'DRAFT',
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT NOT NULL,
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "totalStops" INTEGER NOT NULL DEFAULT 0,
    "totalDrivers" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "dispatch_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dispatch_items" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "locationId" TEXT,
    "zone" TEXT NOT NULL,
    "assignedDriverId" TEXT,
    "urgencyScore" DECIMAL(5,2) NOT NULL,
    "urgencyLevel" TEXT NOT NULL,
    "daysSinceLastVisit" INTEGER NOT NULL,
    "avgConsumption" DECIMAL(10,4),
    "lastInvoiceDate" TIMESTAMP(3),
    "predictedNextDate" TIMESTAMP(3),
    "lastInvoiceQty" INTEGER,
    "totalRevenue" DECIMAL(12,2),
    "totalProfit" DECIMAL(12,2),
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "dispatch_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auto_dispatch_settings" (
    "id" TEXT NOT NULL,
    "autoApprove" BOOLEAN NOT NULL DEFAULT false,
    "urgencyThreshold" INTEGER NOT NULL DEFAULT 60,
    "overdueWeight" DECIMAL(4,2) NOT NULL DEFAULT 0.40,
    "consumptionWeight" DECIMAL(4,2) NOT NULL DEFAULT 0.25,
    "revenueWeight" DECIMAL(4,2) NOT NULL DEFAULT 0.20,
    "daysSinceVisitWeight" DECIMAL(4,2) NOT NULL DEFAULT 0.15,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "auto_dispatch_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "driver_zones_zone_idx" ON "driver_zones"("zone");

-- CreateIndex
CREATE UNIQUE INDEX "driver_zones_driverId_zone_key" ON "driver_zones"("driverId", "zone");

-- CreateIndex
CREATE INDEX "dispatch_items_batchId_zone_idx" ON "dispatch_items"("batchId", "zone");

-- CreateIndex
CREATE INDEX "dispatch_items_urgencyScore_idx" ON "dispatch_items"("urgencyScore");

-- AddForeignKey
ALTER TABLE "driver_zones" ADD CONSTRAINT "driver_zones_driverId_fkey" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dispatch_items" ADD CONSTRAINT "dispatch_items_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "dispatch_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE;
