import React, { useState, useEffect, useCallback } from 'react';
import { api, isAuthRedirect } from '../services/api';
import {
  Send, AlertTriangle, Clock, TrendingUp, Users, Truck,
  ChevronDown, ChevronRight, Check, X, RefreshCw, Settings,
  Zap, Filter, CheckCircle, MapPin, DollarSign, Calendar,
  Info, Plus, Trash2, Star, Flame, Sparkles,
} from 'lucide-react';
import { StatusBadge } from '../components/ui/StatusBadge';
import { MetricCardSkeleton, CardSkeleton } from '../components/ui/Skeleton';
import { EmptyState } from '../components/ui/EmptyState';

// ── Types ───────────────────────────────────────────────────────

interface DriverWithZones {
  id: string;
  name: string;
  zones: { zone: string; isPrimary: boolean }[];
}

interface DispatchSummary {
  totalCustomers: number;
  overdueCount: number;
  dueSoonCount: number;
  readyToDispatch: number;
  autoApprove: boolean;
  urgencyThreshold: number;
  zones: Record<string, { count: number; overdue: number; totalRevenue: number }>;
  uncoveredZones: string[];
  driverCount: number;
  drivers: DriverWithZones[];
}

interface CustomerScore {
  customerId: string;
  customerName: string;
  zone: string;
  city: string;
  locationId: string | null;
  urgencyScore: number;
  urgencyLevel: 'OVERDUE' | 'DUE_SOON' | 'UPCOMING';
  daysSinceLastVisit: number;
  avgConsumption: number;
  lastInvoiceDate: string | null;
  predictedNextDate: string | null;
  lastInvoiceQty: number;
  totalRevenue: number;
  totalProfit: number;
}

interface DispatchBatch {
  id: string;
  name: string;
  dispatchDate: string;
  status: string;
  autoGenerated: boolean;
  totalStops: number;
  totalDrivers: number;
  createdAt: string;
  items: DispatchItem[];
}

interface DispatchItem {
  id: string;
  customerId: string;
  customerName: string;
  zone: string;
  assignedDriverId: string | null;
  driverName: string;
  urgencyScore: number;
  urgencyLevel: string;
  daysSinceLastVisit: number;
  avgConsumption: number;
  lastInvoiceDate: string | null;
  predictedNextDate: string | null;
  lastInvoiceQty: number;
  totalRevenue: number;
  totalProfit: number;
  selected: boolean;
}

// ── Helper Components ───────────────────────────────────────────

function MetricCard({ label, value, sub, icon: Icon, color }: {
  label: string; value: string | number; sub?: string;
  icon: React.ElementType; color: string;
}) {
  return (
    <div className="card p-4">
      <div className="flex items-center gap-3">
        <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${color}`}>
          <Icon size={18} />
        </div>
        <div>
          <p className="text-xs text-muted">{label}</p>
          <p className="text-xl font-bold text-white">{value}</p>
          {sub && <p className="text-[10px] text-muted">{sub}</p>}
        </div>
      </div>
    </div>
  );
}

function UrgencyBar({ score }: { score: number }) {
  let color = 'bg-success';
  if (score >= 75) color = 'bg-danger';
  else if (score >= 50) color = 'bg-warning';
  else if (score >= 25) color = 'bg-primary';

  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-1.5 bg-dark-DEFAULT rounded-full overflow-hidden max-w-[60px]">
        <div className={`h-full rounded-full ${color}`} style={{ width: `${score}%` }} />
      </div>
      <span className="text-xs font-semibold text-white w-8">{score}</span>
    </div>
  );
}

function formatCurrency(n: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
}

function formatDate(d: string | null) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: '2-digit' });
}

function SuggestionMarker({ affinityScore, pickCount, urgencyLevel, totalRevenue }: {
  affinityScore?: number; pickCount?: number;
  urgencyLevel: string; totalRevenue?: number;
}) {
  const tags: { icon: React.ElementType; color: string; label: string }[] = [];
  if ((pickCount ?? 0) >= 3 && (affinityScore ?? 0) >= 0.6) {
    tags.push({ icon: Star, color: 'text-warning', label: 'You pick this often' });
  } else if ((pickCount ?? 0) >= 3) {
    tags.push({ icon: Sparkles, color: 'text-primary', label: 'Familiar customer' });
  }
  if (urgencyLevel === 'OVERDUE') {
    tags.push({ icon: Flame, color: 'text-danger', label: 'Overdue — high priority' });
  }
  if ((totalRevenue ?? 0) >= 20000) {
    tags.push({ icon: DollarSign, color: 'text-success', label: 'High-revenue customer' });
  }
  if (tags.length === 0) return null;
  return (
    <span className="inline-flex items-center gap-0.5 ml-1.5">
      {tags.slice(0, 3).map(({ icon: Icon, color, label }, i) => (
        <span key={i} title={label} className={color}>
          <Icon size={11} />
        </span>
      ))}
    </span>
  );
}

function ScoreInfoTooltip() {
  const [open, setOpen] = useState(false);
  return (
    <div className="relative inline-block">
      <button
        onClick={() => setOpen(!open)}
        className="text-muted hover:text-white transition-colors"
        title="How is the dispatch score calculated?"
      >
        <Info size={14} />
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute z-50 top-6 right-0 w-72 bg-dark-card border border-dark-border rounded-lg shadow-xl p-4 text-xs">
            <h4 className="font-semibold text-white mb-2">Dispatch Score (0–100)</h4>
            <p className="text-muted mb-2">
              Each customer gets a score based on how urgently they need restocking:
            </p>
            <ul className="space-y-1.5 text-muted">
              <li className="flex justify-between">
                <span>Overdue Factor</span>
                <span className="text-white font-semibold">40%</span>
              </li>
              <li className="flex justify-between">
                <span>Avg. Consumption Rate</span>
                <span className="text-white font-semibold">25%</span>
              </li>
              <li className="flex justify-between">
                <span>Revenue Value</span>
                <span className="text-white font-semibold">20%</span>
              </li>
              <li className="flex justify-between">
                <span>Days Since Last Visit</span>
                <span className="text-white font-semibold">15%</span>
              </li>
            </ul>
            <div className="mt-3 pt-2 border-t border-dark-border space-y-1 text-muted">
              <p><span className="inline-block w-2 h-2 rounded-full bg-danger mr-1.5" />75+ = Overdue</p>
              <p><span className="inline-block w-2 h-2 rounded-full bg-warning mr-1.5" />50–74 = Due Soon</p>
              <p><span className="inline-block w-2 h-2 rounded-full bg-primary mr-1.5" />25–49 = Upcoming</p>
              <p><span className="inline-block w-2 h-2 rounded-full bg-success mr-1.5" />0–24 = Low Priority</p>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function DriverZoneManager({ drivers: rawDrivers, allZones, onSave }: {
  drivers: DriverWithZones[];
  allZones: string[];
  onSave: (driverId: string, zones: { zone: string; isPrimary?: boolean }[]) => Promise<void>;
}) {
  // Dedupe drivers by name, keeping the entry with more zones (backend seed
  // sometimes creates orphan driver rows with the same name but no zones).
  const drivers = Array.from(
    rawDrivers.reduce((m, d) => {
      const existing = m.get(d.name);
      if (!existing || d.zones.length > existing.zones.length) m.set(d.name, d);
      return m;
    }, new Map<string, DriverWithZones>()).values()
  );
  // One-click add/remove. No Edit mode, no Save button — every chip action persists immediately.
  const [openPickerId, setOpenPickerId] = useState<string | null>(null);
  const [pickerSearch, setPickerSearch] = useState('');

  const addZone = async (driver: DriverWithZones, zone: string) => {
    if (driver.zones.some(z => z.zone === zone)) return;
    const next = [...driver.zones, { zone, isPrimary: driver.zones.length === 0 }];
    await onSave(driver.id, next);
    setOpenPickerId(null);
    setPickerSearch('');
  };

  const removeZone = async (driver: DriverWithZones, zone: string) => {
    const next = driver.zones.filter(z => z.zone !== zone);
    if (next.length > 0 && !next.some(z => z.isPrimary)) next[0].isPrimary = true;
    await onSave(driver.id, next);
  };

  const setPrimary = async (driver: DriverWithZones, zone: string) => {
    const next = driver.zones.map(z => ({ zone: z.zone, isPrimary: z.zone === zone }));
    await onSave(driver.id, next);
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h4 className="text-xs font-semibold text-white flex items-center gap-2">
          <Truck size={13} />
          Driver Zone Assignments
        </h4>
        <span className="text-[10px] text-muted">Click ★ to set primary · × to remove · + to add</span>
      </div>
      <div className="space-y-2">
        {drivers.map(driver => {
          const available = allZones.filter(z => !driver.zones.some(dz => dz.zone === z));
          const filtered = pickerSearch.trim()
            ? available.filter(z => z.toLowerCase().includes(pickerSearch.toLowerCase()))
            : available;
          const pickerOpen = openPickerId === driver.id;
          return (
            <div key={driver.id} className="bg-dark rounded-lg p-3 border border-dark-border">
              <div className="flex items-start gap-3">
                <div className="flex items-center gap-2 pt-1 min-w-[140px]">
                  <Users size={13} className="text-primary" />
                  <span className="text-xs font-semibold text-white">{driver.name}</span>
                </div>
                <div className="flex-1 flex flex-wrap gap-1.5 items-center">
                  {driver.zones.length === 0 && (
                    <span className="text-[10px] text-warning">No zones assigned</span>
                  )}
                  {driver.zones.map(z => (
                    <span
                      key={z.zone}
                      className={`inline-flex items-center gap-1 pl-2 pr-1 py-0.5 rounded text-[10px] font-medium ${
                        z.isPrimary
                          ? 'bg-primary/20 text-primary border border-primary/30'
                          : 'bg-dark-card text-white border border-dark-border'
                      }`}
                    >
                      <button
                        onClick={() => setPrimary(driver, z.zone)}
                        title={z.isPrimary ? 'Primary zone' : 'Click to set as primary'}
                        className="flex items-center gap-0.5 hover:opacity-80"
                      >
                        {z.isPrimary && <Star size={8} />}
                        {z.zone}
                      </button>
                      <button
                        onClick={() => removeZone(driver, z.zone)}
                        className="hover:text-danger p-0.5"
                        title="Remove zone"
                      >
                        <X size={9} />
                      </button>
                    </span>
                  ))}
                  <div className="relative">
                    <button
                      onClick={() => {
                        setOpenPickerId(pickerOpen ? null : driver.id);
                        setPickerSearch('');
                      }}
                      className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-dark border border-dashed border-dark-border text-muted hover:text-white hover:border-primary/50"
                    >
                      <Plus size={10} /> Add zone
                    </button>
                    {pickerOpen && (
                      <>
                        <div className="fixed inset-0 z-40" onClick={() => setOpenPickerId(null)} />
                        <div className="absolute z-50 top-full left-0 mt-1 w-56 bg-dark-card border border-dark-border rounded-lg shadow-xl p-1.5">
                          <input
                            autoFocus
                            type="text"
                            value={pickerSearch}
                            onChange={e => setPickerSearch(e.target.value)}
                            placeholder="Search or type new zone..."
                            onKeyDown={e => {
                              if (e.key === 'Enter') {
                                const z = pickerSearch.trim().toUpperCase();
                                if (z) addZone(driver, z);
                              }
                              if (e.key === 'Escape') setOpenPickerId(null);
                            }}
                            className="w-full h-7 px-2 bg-dark border border-dark-border rounded text-xs text-white placeholder:text-muted focus:border-primary focus:outline-none mb-1"
                          />
                          <div className="max-h-52 overflow-y-auto">
                            {filtered.length === 0 ? (
                              <p className="text-[10px] text-muted p-2">
                                {pickerSearch
                                  ? `Press Enter to add "${pickerSearch.toUpperCase()}"`
                                  : 'No more zones'}
                              </p>
                            ) : (
                              filtered.map(z => (
                                <button
                                  key={z}
                                  onClick={() => addZone(driver, z)}
                                  className="w-full flex items-center gap-2 px-2 py-1 rounded text-xs text-white hover:bg-dark-border/40"
                                >
                                  <MapPin size={10} className="text-primary" />
                                  {z}
                                </button>
                              ))
                            )}
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ── Dispatch Driver View ────────────────────────────────────────
// Driver chips at the top; selecting one auto-selects their zones.
// Zone chips underneath — click to add/remove zones from the active driver.
// Zone-grouped customer rows below (Scores-tab style). Click a row to assign
// the customer to the active driver; row shows the currently assigned driver.

function DispatchDriverView({ batch, drivers: rawDrivers, allZones, affinity, onAssign, onExclude, onInclude, onAddZoneToDriver, onRemoveZoneFromDriver }: {
  batch: DispatchBatch;
  drivers: DriverWithZones[];
  allZones: string[];
  affinity: Record<string, { affinityScore: number; pickCount: number }>;
  onAssign: (itemId: string, driverId: string | null) => void;
  onExclude: (itemId: string) => void;
  onInclude: (itemId: string) => void;
  onAddZoneToDriver: (driverId: string, zone: string) => Promise<void>;
  onRemoveZoneFromDriver: (driverId: string, zone: string) => Promise<void>;
}) {
  // Dedupe by name — backend sometimes returns same-named driver rows. Keep
  // the entry with the most zones (or items, as a tie-breaker) for each name.
  const driverIdsWithItems = new Set(batch.items.map(i => i.assignedDriverId).filter(Boolean));
  const drivers = Array.from(
    rawDrivers.reduce((m, d) => {
      const existing = m.get(d.name);
      const dScore = d.zones.length * 100 + (driverIdsWithItems.has(d.id) ? 1 : 0);
      const eScore = existing ? existing.zones.length * 100 + (driverIdsWithItems.has(existing.id) ? 1 : 0) : -1;
      if (!existing || dScore > eScore) m.set(d.name, d);
      return m;
    }, new Map<string, DriverWithZones>()).values()
  );
  const isDraft = batch.status === 'DRAFT';
  const [activeDriverId, setActiveDriverId] = useState<string | null>(drivers[0]?.id ?? null);
  const [selectedZones, setSelectedZones] = useState<Set<string>>(new Set());
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedZones, setExpandedZones] = useState<Set<string>>(new Set());
  const [addZoneOpen, setAddZoneOpen] = useState(false);

  const activeDriver = drivers.find(d => d.id === activeDriverId) ?? null;
  const activeDriverZones = activeDriver?.zones.map(z => z.zone) ?? [];

  // When active driver changes, default the zone filter to the driver's zones.
  useEffect(() => {
    setSelectedZones(new Set(activeDriverZones));
    setExpandedZones(new Set(activeDriverZones));
    setAddZoneOpen(false);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeDriverId, activeDriver?.zones.length]);

  const toggleZoneFilter = (zone: string) => {
    setSelectedZones(prev => {
      const next = new Set(prev);
      next.has(zone) ? next.delete(zone) : next.add(zone);
      return next;
    });
  };

  const toggleExpanded = (zone: string) => {
    setExpandedZones(prev => {
      const next = new Set(prev);
      next.has(zone) ? next.delete(zone) : next.add(zone);
      return next;
    });
  };

  const driverNameById = new Map(drivers.map(d => [d.id, d.name] as const));
  const zoneDistribution: Record<string, { total: number; assignedToActive: number; assignedElsewhere: number }> = {};
  for (const item of batch.items) {
    const z = item.zone || '—';
    if (!zoneDistribution[z]) zoneDistribution[z] = { total: 0, assignedToActive: 0, assignedElsewhere: 0 };
    zoneDistribution[z].total += 1;
    if (item.assignedDriverId === activeDriverId) zoneDistribution[z].assignedToActive += 1;
    else if (item.assignedDriverId) zoneDistribution[z].assignedElsewhere += 1;
  }

  // Filter items by zone + search
  const zonesToShow = selectedZones.size > 0 ? selectedZones : new Set(Object.keys(zoneDistribution));
  const q = searchQuery.trim().toLowerCase();
  const filteredItems = batch.items.filter(i => {
    if (!zonesToShow.has(i.zone)) return false;
    if (q && !i.customerName.toLowerCase().includes(q)) return false;
    return true;
  });

  // Group filtered items by zone
  const byZone: Record<string, DispatchItem[]> = {};
  for (const i of filteredItems) {
    (byZone[i.zone] = byZone[i.zone] || []).push(i);
  }
  for (const arr of Object.values(byZone)) {
    arr.sort((a, b) => Number(b.urgencyScore) - Number(a.urgencyScore));
  }

  // Metrics for the active driver
  const activeDriverItems = batch.items.filter(i => i.assignedDriverId === activeDriverId && i.selected);
  const unassignedCount = batch.items.filter(i => i.selected && !i.assignedDriverId).length;

  const zonesAvailableToAdd = allZones.filter(z => !activeDriverZones.includes(z));

  return (
    <div className="space-y-3">
      {/* ── Driver Tabs (top) ─────────────────────────────────── */}
      <div className="card p-3">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-[10px] font-semibold text-muted uppercase tracking-wider mr-1">Driver</span>
          {drivers.length === 0 ? (
            <span className="text-xs text-warning">No drivers — add some in Overview</span>
          ) : (
            drivers.map(d => {
              const count = batch.items.filter(i => i.assignedDriverId === d.id && i.selected).length;
              const active = d.id === activeDriverId;
              return (
                <button
                  key={d.id}
                  onClick={() => setActiveDriverId(d.id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                    active
                      ? 'bg-primary text-dark-DEFAULT'
                      : 'bg-dark border border-dark-border text-muted hover:text-white hover:border-primary/50'
                  }`}
                >
                  <Users size={12} />
                  <span>{d.name}</span>
                  <span className={`ml-0.5 px-1.5 py-0.5 rounded-full text-[9px] font-semibold ${
                    active ? 'bg-dark-DEFAULT/20 text-dark-DEFAULT' : 'bg-dark-border/40 text-muted'
                  }`}>{count}</span>
                </button>
              );
            })
          )}
          {unassignedCount > 0 && (
            <span className="ml-auto text-[10px] text-warning flex items-center gap-1">
              <AlertTriangle size={10} />
              {unassignedCount} unassigned
            </span>
          )}
        </div>

        {/* Active driver's zones — always visible, one-click add/remove */}
        {activeDriver && (
          <div className="mt-3 pt-3 border-t border-dark-border">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-[10px] font-semibold text-muted uppercase tracking-wider mr-1">
                {activeDriver.name}'s Zones
              </span>
              {activeDriverZones.length === 0 && (
                <span className="text-[10px] text-warning">No zones assigned</span>
              )}
              {activeDriver.zones.map(z => (
                <span
                  key={z.zone}
                  className={`inline-flex items-center gap-1 px-2 py-1 rounded text-[10px] font-semibold ${
                    z.isPrimary
                      ? 'bg-primary/20 text-primary border border-primary/30'
                      : 'bg-dark-border/40 text-white border border-dark-border'
                  }`}
                >
                  {z.zone}{z.isPrimary ? ' ★' : ''}
                  {isDraft && (
                    <button
                      onClick={() => onRemoveZoneFromDriver(activeDriver.id, z.zone)}
                      className="hover:text-danger"
                      title="Remove zone from driver"
                    >
                      <X size={9} />
                    </button>
                  )}
                </span>
              ))}
              {isDraft && zonesAvailableToAdd.length > 0 && (
                <div className="relative">
                  <button
                    onClick={() => setAddZoneOpen(!addZoneOpen)}
                    className="inline-flex items-center gap-1 px-2 py-1 rounded text-[10px] font-semibold bg-dark border border-dashed border-dark-border text-muted hover:text-white hover:border-primary/50"
                  >
                    <Plus size={10} /> Add zone
                  </button>
                  {addZoneOpen && (
                    <>
                      <div className="fixed inset-0 z-40" onClick={() => setAddZoneOpen(false)} />
                      <div className="absolute z-50 top-full left-0 mt-1 w-48 max-h-64 overflow-y-auto bg-dark-card border border-dark-border rounded-lg shadow-xl p-1">
                        {zonesAvailableToAdd.map(z => (
                          <button
                            key={z}
                            onClick={async () => { await onAddZoneToDriver(activeDriver.id, z); setAddZoneOpen(false); }}
                            className="w-full flex items-center gap-2 px-2 py-1.5 rounded text-xs text-white hover:bg-dark-border/40"
                          >
                            <MapPin size={10} className="text-primary" />
                            {z}
                          </button>
                        ))}
                      </div>
                    </>
                  )}
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* ── Zone filter + search ──────────────────────────────── */}
      <div className="card p-3 space-y-2.5">
        <div className="flex items-center gap-3 flex-wrap">
          <div className="relative flex-1 min-w-[200px] max-w-[320px]">
            <Filter size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-muted pointer-events-none" />
            <input
              type="text"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search customer..."
              className="w-full h-8 pl-8 pr-3 bg-dark border border-dark-border rounded text-xs text-white placeholder:text-muted focus:border-primary focus:outline-none"
            />
          </div>
          <span className="text-[10px] text-muted">
            {filteredItems.length} of {batch.items.length} · {Object.keys(byZone).length} zones
          </span>
          {selectedZones.size > 0 && (
            <button
              onClick={() => setSelectedZones(new Set())}
              className="text-[10px] text-muted hover:text-white underline"
            >
              Clear zone filter
            </button>
          )}
        </div>
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className="text-[10px] text-muted uppercase tracking-wider mr-1">Zones</span>
          {Object.entries(zoneDistribution).sort(([a], [b]) => a.localeCompare(b)).map(([zone, info]) => {
            const isSelected = selectedZones.has(zone);
            const inActiveDriver = activeDriverZones.includes(zone);
            return (
              <button
                key={zone}
                onClick={() => toggleZoneFilter(zone)}
                className={`inline-flex items-center gap-1 px-2 py-1 rounded text-[10px] font-medium border transition-colors ${
                  isSelected
                    ? 'bg-primary/15 text-primary border-primary/40'
                    : inActiveDriver
                      ? 'bg-dark border-primary/20 text-muted hover:text-white'
                      : 'bg-dark border-dark-border text-muted hover:text-white hover:border-primary/40'
                }`}
                title={inActiveDriver ? `${activeDriver?.name}'s zone` : 'Click to include zone'}
              >
                {inActiveDriver && <Star size={9} className="text-primary" />}
                {zone}
                <span className="text-[9px] opacity-70">{info.total}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Zone-grouped customer list ────────────────────────── */}
      {filteredItems.length === 0 ? (
        <div className="card">
          <EmptyState
            icon={Users}
            title="No customers match"
            description={activeDriver ? `Try selecting more zones for ${activeDriver.name} or adjusting the search.` : 'Pick a driver to begin.'}
          />
        </div>
      ) : (
        Object.entries(byZone).sort(([a], [b]) => a.localeCompare(b)).map(([zone, items]) => {
          const isExpanded = expandedZones.has(zone);
          const inActiveDriver = activeDriverZones.includes(zone);
          const overdueCount = items.filter(i => i.urgencyLevel === 'OVERDUE').length;
          return (
            <div key={zone} className="card overflow-hidden">
              <button
                onClick={() => toggleExpanded(zone)}
                className="w-full flex items-center justify-between px-5 py-3 hover:bg-dark-border/20 transition-colors"
              >
                <div className="flex items-center gap-3">
                  {isExpanded ? <ChevronDown size={14} className="text-muted" /> : <ChevronRight size={14} className="text-muted" />}
                  <MapPin size={14} className={inActiveDriver ? 'text-primary' : 'text-muted'} />
                  <span className="text-sm font-semibold text-white">Zone {zone}</span>
                  {inActiveDriver && <Star size={11} className="text-primary" />}
                  <span className="text-xs text-muted">{items.length} customers</span>
                  {overdueCount > 0 && <span className="badge badge-danger text-[10px]">{overdueCount} overdue</span>}
                </div>
                {isDraft && !inActiveDriver && activeDriver && (
                  <span
                    role="button"
                    onClick={(e) => { e.stopPropagation(); onAddZoneToDriver(activeDriver.id, zone); }}
                    className="text-[10px] text-primary hover:underline inline-flex items-center gap-1 cursor-pointer"
                  >
                    <Plus size={10} /> Give to {activeDriver.name}
                  </span>
                )}
              </button>
              {isExpanded && (
                <table className="w-full">
                  <thead>
                    <tr className="border-t border-dark-border">
                      <th className="th">Customer</th>
                      <th className="th text-center">
                        <span className="inline-flex items-center gap-1">Score <ScoreInfoTooltip /></span>
                      </th>
                      <th className="th">Status</th>
                      <th className="th text-center">Days</th>
                      <th className="th text-right">Revenue</th>
                      <th className="th">Assigned</th>
                      <th className="th w-10"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {items.map(item => {
                      const a = affinity[item.customerId];
                      const assignedToActive = item.assignedDriverId === activeDriverId;
                      const assignedElsewhere = item.assignedDriverId && !assignedToActive;
                      return (
                        <tr
                          key={item.id}
                          className={`tr cursor-pointer ${!item.selected ? 'opacity-40' : ''} ${assignedToActive ? 'bg-primary/5' : ''}`}
                          onClick={() => {
                            if (!isDraft || !activeDriverId) return;
                            if (assignedToActive) {
                              // Clicking an already-active row unassigns
                              onAssign(item.id, null);
                            } else {
                              onAssign(item.id, activeDriverId);
                            }
                          }}
                        >
                          <td className="td">
                            <div className="flex items-center gap-1.5">
                              {assignedToActive && <Check size={11} className="text-primary" />}
                              <span className="font-semibold text-white text-xs">{item.customerName}</span>
                              <SuggestionMarker
                                affinityScore={a?.affinityScore}
                                pickCount={a?.pickCount}
                                urgencyLevel={item.urgencyLevel}
                                totalRevenue={Number(item.totalRevenue)}
                              />
                            </div>
                          </td>
                          <td className="td"><UrgencyBar score={Number(item.urgencyScore)} /></td>
                          <td className="td"><StatusBadge status={item.urgencyLevel} /></td>
                          <td className="td text-center">
                            <span className={`text-xs font-semibold ${item.daysSinceLastVisit > 30 ? 'text-danger' : 'text-white'}`}>
                              {item.daysSinceLastVisit}d
                            </span>
                          </td>
                          <td className="td text-right text-muted text-xs">{formatCurrency(Number(item.totalRevenue))}</td>
                          <td className="td">
                            {assignedToActive ? (
                              <span className="text-[10px] text-primary font-semibold">{activeDriver?.name}</span>
                            ) : assignedElsewhere ? (
                              <span className="text-[10px] text-warning">{driverNameById.get(item.assignedDriverId!) || '—'}</span>
                            ) : (
                              <span className="text-[10px] text-muted">—</span>
                            )}
                          </td>
                          <td className="td text-right">
                            {isDraft && item.selected && (
                              <button
                                onClick={(e) => { e.stopPropagation(); onExclude(item.id); }}
                                className="text-muted hover:text-danger"
                                title="Exclude from dispatch"
                              >
                                <X size={12} />
                              </button>
                            )}
                            {isDraft && !item.selected && (
                              <button
                                onClick={(e) => { e.stopPropagation(); onInclude(item.id); }}
                                className="text-[10px] text-primary hover:underline"
                                title="Re-include"
                              >
                                include
                              </button>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              )}
            </div>
          );
        })
      )}

      {/* ── Active driver summary ─────────────────────────────── */}
      {activeDriver && activeDriverItems.length > 0 && (
        <div className="card p-3 border-primary/30 bg-primary/5">
          <div className="flex items-center gap-2 text-[10px] text-muted">
            <CheckCircle size={11} className="text-primary" />
            <span className="font-semibold text-white">{activeDriver.name}</span>
            <span>has {activeDriverItems.length} stops assigned</span>
            <span>· click an already-assigned row to unassign</span>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main Page ───────────────────────────────────────────────────

export default function AutoDispatchPage() {
  const [tab, setTab] = useState<'overview' | 'scores' | 'batch' | 'settings'>('overview');
  const [summary, setSummary] = useState<DispatchSummary | null>(null);
  const [scores, setScores] = useState<CustomerScore[]>([]);
  const [batch, setBatch] = useState<DispatchBatch | null>(null);
  const [batches, setBatches] = useState<any[]>([]);
  const [settings, setSettings] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [approving, setApproving] = useState(false);
  const [zoneFilter, setZoneFilter] = useState<string>('ALL');
  const [urgencyFilter, setUrgencyFilter] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedZones, setExpandedZones] = useState<Set<string>>(new Set());
  const [showSettings, setShowSettings] = useState(false);
  // Habit-learning state: shows ★ markers but never auto-selects
  const [affinity, setAffinity] = useState<Record<string, { affinityScore: number; pickCount: number }>>({});

  // ── Data Loading ──────────────────────────────────────────────

  const loadOverview = useCallback(async () => {
    try {
      const [sum, batchList] = await Promise.all([
        api.getDispatchSummary(),
        api.getDispatchBatches(5),
      ]);
      setSummary(sum);
      setBatches(batchList);
    } catch (err) {
      if (!isAuthRedirect(err)) console.error(err);
    }
  }, []);

  const loadScores = useCallback(async () => {
    try {
      const data = await api.getDispatchScores();
      setScores(data);
    } catch (err) {
      if (!isAuthRedirect(err)) console.error(err);
    }
  }, []);

  const loadSettings = useCallback(async () => {
    try {
      const data = await api.getDispatchSettings();
      setSettings(data);
    } catch (err) {
      if (!isAuthRedirect(err)) console.error(err);
    }
  }, []);

  const loadAffinity = useCallback(async () => {
    try {
      const data = await api.getDispatchAffinity();
      setAffinity(data || {});
    } catch (err) {
      if (!isAuthRedirect(err)) console.error(err);
    }
  }, []);

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      await Promise.all([loadOverview(), loadScores(), loadSettings(), loadAffinity()]);
      setLoading(false);
    };
    load();
  }, [loadOverview, loadScores, loadSettings, loadAffinity]);

  // ── Actions ───────────────────────────────────────────────────

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const today = new Date();
      today.setDate(today.getDate() + 1); // default to tomorrow
      const zones = zoneFilter !== 'ALL' ? [zoneFilter] : undefined;
      const result = await api.generateDispatchBatch({
        dispatchDate: today.toISOString().split('T')[0],
        zones,
      });
      setBatch(result);
      setTab('batch');
    } catch (err: any) {
      alert(err.message || 'Failed to generate dispatch');
    } finally {
      setGenerating(false);
    }
  };

  const handleLoadBatch = async (batchId: string) => {
    try {
      const result = await api.getDispatchBatch(batchId);
      setBatch(result);
      setTab('batch');
    } catch (err: any) {
      alert(err.message || 'Failed to load batch');
    }
  };

  const handleToggleItem = async (itemId: string, selected: boolean) => {
    if (!batch) return;
    try {
      await api.updateDispatchItem(batch.id, itemId, { selected });
      setBatch(prev => prev ? {
        ...prev,
        items: prev.items.map(i => i.id === itemId ? { ...i, selected } : i),
      } : null);
    } catch (err: any) {
      console.error(err);
    }
  };

  const handleApprove = async () => {
    if (!batch) return;
    setApproving(true);
    try {
      // Record selection history FIRST so the system learns habits even if approve fails
      try {
        await api.recordDispatchSelections(batch.items.map(i => ({
          customerId: i.customerId,
          batchId: batch.id,
          urgencyScore: Number(i.urgencyScore),
          selected: i.selected,
          zone: i.zone,
        })));
        await loadAffinity();
      } catch (e) {
        console.warn('Failed to record selections for habit learning', e);
      }
      await api.approveDispatchBatch(batch.id);
      setBatch(prev => prev ? { ...prev, status: 'DISPATCHED' } : null);
      await loadOverview();
    } catch (err: any) {
      alert(err.message || 'Failed to approve batch');
    } finally {
      setApproving(false);
    }
  };

  // ── Chip actions (Kanban lane view) ───────────────────────────

  const handleAssignDriver = async (itemId: string, driverId: string | null) => {
    if (!batch) return;
    const driverName = driverId
      ? summary?.drivers.find(d => d.id === driverId)?.name || '—'
      : 'Unassigned';
    // Optimistic update
    setBatch(prev => prev ? {
      ...prev,
      items: prev.items.map(i => i.id === itemId
        ? { ...i, assignedDriverId: driverId, driverName, selected: true }
        : i),
    } : null);
    if (driverId) {
      await api.updateDispatchItem(batch.id, itemId, { assignedDriverId: driverId }).catch(() => {});
    }
    // Always make sure it's included once assigned
    await api.updateDispatchItem(batch.id, itemId, { selected: true }).catch(() => {});
  };

  const handleExcludeItem = async (itemId: string) => {
    if (!batch) return;
    setBatch(prev => prev ? {
      ...prev,
      items: prev.items.map(i => i.id === itemId ? { ...i, selected: false } : i),
    } : null);
    await api.updateDispatchItem(batch.id, itemId, { selected: false }).catch(() => {});
  };

  const handleIncludeItem = async (itemId: string) => {
    if (!batch) return;
    setBatch(prev => prev ? {
      ...prev,
      items: prev.items.map(i => i.id === itemId ? { ...i, selected: true } : i),
    } : null);
    await api.updateDispatchItem(batch.id, itemId, { selected: true }).catch(() => {});
  };

  const handleCancel = async () => {
    if (!batch) return;
    try {
      await api.cancelDispatchBatch(batch.id);
      setBatch(prev => prev ? { ...prev, status: 'CANCELLED' } : null);
      await loadOverview();
    } catch (err: any) {
      alert(err.message || 'Failed to cancel');
    }
  };

  const handleSaveSettings = async () => {
    if (!settings) return;
    try {
      const updated = await api.updateDispatchSettings({
        autoApprove: settings.autoApprove,
        urgencyThreshold: settings.urgencyThreshold,
      });
      setSettings(updated);
      setShowSettings(false);
      await Promise.all([loadOverview(), loadScores()]);
    } catch (err: any) {
      alert(err.message || 'Failed to save settings');
    }
  };

  // ── Filtering ─────────────────────────────────────────────────

  const allZones = [...new Set(scores.map(s => s.zone))].sort();

  const filteredScores = scores.filter(s => {
    if (zoneFilter !== 'ALL' && s.zone !== zoneFilter) return false;
    if (urgencyFilter !== 'ALL' && s.urgencyLevel !== urgencyFilter) return false;
    if (searchQuery && !s.customerName.toLowerCase().includes(searchQuery.toLowerCase())) return false;
    return true;
  });

  // Group by zone for overview
  const scoresByZone = filteredScores.reduce((acc, s) => {
    (acc[s.zone] = acc[s.zone] || []).push(s);
    return acc;
  }, {} as Record<string, CustomerScore[]>);

  const toggleZone = (zone: string) => {
    setExpandedZones(prev => {
      const next = new Set(prev);
      next.has(zone) ? next.delete(zone) : next.add(zone);
      return next;
    });
  };

  // ── Render ────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="p-6 space-y-5 max-w-[1400px]">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {Array.from({ length: 4 }).map((_, i) => <MetricCardSkeleton key={i} />)}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {Array.from({ length: 4 }).map((_, i) => <CardSkeleton key={i} lines={5} />)}
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-5 max-w-[1400px]">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="page-title flex items-center gap-2">
            <Zap size={20} className="text-primary" />
            Auto-Dispatch
          </h1>
          <p className="text-xs text-muted mt-0.5">
            AI-powered route generation based on customer demand patterns
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => { setLoading(true); Promise.all([loadOverview(), loadScores()]).then(() => setLoading(false)); }}
            className="btn-ghost text-xs"
          >
            <RefreshCw size={13} />
          </button>
          <button onClick={() => setShowSettings(!showSettings)} className="btn-ghost text-xs">
            <Settings size={13} />
            Settings
          </button>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="btn-primary text-xs"
          >
            <Send size={13} />
            {generating ? 'Generating...' : 'Generate Dispatch'}
          </button>
        </div>
      </div>

      {/* Settings Panel */}
      {showSettings && settings && (
        <div className="card p-5 border-primary/30 space-y-5">
          <h3 className="text-sm font-semibold text-white">Dispatch Settings</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs text-muted mb-1">Urgency Threshold</label>
              <input
                type="number"
                min={0}
                max={100}
                value={settings.urgencyThreshold}
                onChange={e => setSettings({ ...settings, urgencyThreshold: parseInt(e.target.value) || 0 })}
                className="w-full h-9 px-3 bg-dark border border-dark-border rounded-lg text-sm text-white focus:border-primary focus:outline-none"
              />
              <p className="text-[10px] text-muted mt-1">Customers above this score are auto-selected (0-100)</p>
            </div>
            <div>
              <label className="block text-xs text-muted mb-1">Auto-Approve</label>
              <button
                onClick={() => setSettings({ ...settings, autoApprove: !settings.autoApprove })}
                className={`flex items-center gap-2 h-9 px-4 rounded-lg text-sm font-medium transition-colors ${
                  settings.autoApprove
                    ? 'bg-success/20 text-success border border-success/30'
                    : 'bg-dark border border-dark-border text-muted'
                }`}
              >
                {settings.autoApprove ? <Check size={14} /> : <X size={14} />}
                {settings.autoApprove ? 'On — Routes dispatched instantly' : 'Off — Manual approval required'}
              </button>
            </div>
            <div className="flex items-end">
              <button onClick={handleSaveSettings} className="btn-primary text-xs h-9">
                Save Settings
              </button>
            </div>
          </div>

          {/* Driver Zone Assignment */}
          {summary?.drivers && (
            <div className="pt-4 border-t border-dark-border">
              <DriverZoneManager
                drivers={summary.drivers}
                allZones={[...new Set([...allZones, ...Object.keys(summary.zones || {})])].sort()}
                onSave={async (driverId, zones) => {
                  await api.assignDriverZones(driverId, zones);
                  await loadOverview();
                }}
              />
            </div>
          )}
        </div>
      )}

      {/* Tabs */}
      <div className="flex items-center gap-1 bg-dark-card border border-dark-border rounded-lg p-1 w-fit">
        {(['overview', 'scores', 'batch'] as const).map(t => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-1.5 rounded-md text-xs font-medium transition-colors capitalize ${
              tab === t ? 'bg-primary text-dark-DEFAULT' : 'text-muted hover:text-white'
            }`}
          >
            {t === 'batch' ? 'Dispatch Batch' : t}
          </button>
        ))}
      </div>

      {/* ── Overview Tab ───────────────────────────────────────── */}
      {tab === 'overview' && summary && (
        <>
          {/* Metric Cards */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <MetricCard
              label="Overdue"
              value={summary.overdueCount}
              sub="Need immediate attention"
              icon={AlertTriangle}
              color="bg-danger/20 text-danger"
            />
            <MetricCard
              label="Due Soon"
              value={summary.dueSoonCount}
              sub="Within 7 days"
              icon={Clock}
              color="bg-warning/20 text-warning"
            />
            <MetricCard
              label="Ready to Dispatch"
              value={summary.readyToDispatch}
              sub={`Score >= ${summary.urgencyThreshold}`}
              icon={Send}
              color="bg-primary/20 text-primary"
            />
            <MetricCard
              label="Active Drivers"
              value={summary.driverCount}
              sub={`${Object.keys(summary.zones).length} zones covered`}
              icon={Truck}
              color="bg-success/20 text-success"
            />
          </div>

          {/* Uncovered Zones Warning */}
          {summary.uncoveredZones.length > 0 && (
            <div className="card p-4 border-warning/30 bg-warning/5">
              <div className="flex items-center gap-2">
                <AlertTriangle size={14} className="text-warning" />
                <span className="text-xs font-semibold text-warning">Uncovered Zones</span>
              </div>
              <p className="text-xs text-muted mt-1">
                No drivers assigned to: {summary.uncoveredZones.join(', ')}
              </p>
            </div>
          )}

          {/* Driver-Zone Lanes — always visible so zone assignment is one click, not buried */}
          {summary.drivers && summary.drivers.length > 0 && (
            <div className="card p-5">
              <DriverZoneManager
                drivers={summary.drivers}
                allZones={[...new Set([...allZones, ...Object.keys(summary.zones || {})])].sort()}
                onSave={async (driverId, zones) => {
                  await api.assignDriverZones(driverId, zones);
                  await loadOverview();
                }}
              />
            </div>
          )}

          {/* Zone Breakdown */}
          <div className="card overflow-hidden">
            <div className="px-5 py-3 border-b border-dark-border">
              <h3 className="text-sm font-semibold text-white">Zone Breakdown</h3>
            </div>
            <table className="w-full">
              <thead>
                <tr className="border-b border-dark-border">
                  <th className="th">Zone</th>
                  <th className="th text-center">Customers</th>
                  <th className="th text-center">Overdue</th>
                  <th className="th text-right">Total Revenue</th>
                </tr>
              </thead>
              <tbody>
                {Object.entries(summary.zones)
                  .sort(([, a], [, b]) => b.overdue - a.overdue)
                  .map(([zone, data]) => (
                    <tr key={zone} className="tr cursor-pointer" onClick={() => { setZoneFilter(zone); setTab('scores'); }}>
                      <td className="td">
                        <div className="flex items-center gap-2">
                          <MapPin size={12} className="text-primary" />
                          <span className="font-semibold text-white">{zone}</span>
                        </div>
                      </td>
                      <td className="td text-center text-muted">{data.count}</td>
                      <td className="td text-center">
                        {data.overdue > 0 ? (
                          <span className="text-danger font-semibold">{data.overdue}</span>
                        ) : (
                          <span className="text-muted">0</span>
                        )}
                      </td>
                      <td className="td text-right text-muted">{formatCurrency(data.totalRevenue)}</td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>

          {/* Recent Batches */}
          {batches.length > 0 && (
            <div className="card overflow-hidden">
              <div className="px-5 py-3 border-b border-dark-border">
                <h3 className="text-sm font-semibold text-white">Recent Dispatches</h3>
              </div>
              <table className="w-full">
                <thead>
                  <tr className="border-b border-dark-border">
                    <th className="th">Batch</th>
                    <th className="th">Date</th>
                    <th className="th">Status</th>
                    <th className="th text-center">Stops</th>
                    <th className="th text-center">Drivers</th>
                    <th className="th">Created</th>
                  </tr>
                </thead>
                <tbody>
                  {batches.map((b: any) => (
                    <tr key={b.id} className="tr cursor-pointer" onClick={() => handleLoadBatch(b.id)}>
                      <td className="td font-semibold text-white">{b.name}</td>
                      <td className="td text-muted text-xs">{formatDate(b.dispatchDate)}</td>
                      <td className="td"><StatusBadge status={b.status} /></td>
                      <td className="td text-center text-muted">{b.totalStops}</td>
                      <td className="td text-center text-muted">{b.totalDrivers}</td>
                      <td className="td text-xs text-muted">{formatDate(b.createdAt)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* ── Scores Tab ─────────────────────────────────────────── */}
      {tab === 'scores' && (
        <>
          {/* Filters */}
          <div className="flex flex-wrap items-center gap-3">
            <div className="relative">
              <Filter size={12} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted pointer-events-none" />
              <select
                value={zoneFilter}
                onChange={e => setZoneFilter(e.target.value)}
                className="h-8 pl-8 pr-8 bg-dark-card border border-dark-border rounded-lg text-xs text-white appearance-none cursor-pointer focus:border-primary focus:outline-none"
              >
                <option value="ALL">All Zones</option>
                {allZones.map(z => <option key={z} value={z}>{z}</option>)}
              </select>
            </div>
            <select
              value={urgencyFilter}
              onChange={e => setUrgencyFilter(e.target.value)}
              className="h-8 px-3 bg-dark-card border border-dark-border rounded-lg text-xs text-white appearance-none cursor-pointer focus:border-primary focus:outline-none"
            >
              <option value="ALL">All Urgency</option>
              <option value="OVERDUE">Overdue</option>
              <option value="DUE_SOON">Due Soon</option>
              <option value="UPCOMING">Upcoming</option>
            </select>
            <input
              type="text"
              placeholder="Search customer..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="h-8 px-3 w-56 bg-dark-card border border-dark-border rounded-lg text-xs text-white placeholder:text-muted focus:border-primary focus:outline-none"
            />
            <span className="text-xs text-muted ml-auto">{filteredScores.length} customers</span>
          </div>

          {/* Grouped by Zone */}
          {Object.entries(scoresByZone).sort(([a], [b]) => a.localeCompare(b)).map(([zone, customers]) => {
            const overdueCount = customers.filter(c => c.urgencyLevel === 'OVERDUE').length;
            const isExpanded = expandedZones.has(zone);

            return (
              <div key={zone} className="card overflow-hidden">
                <button
                  onClick={() => toggleZone(zone)}
                  className="w-full flex items-center justify-between px-5 py-3 hover:bg-dark-border/20 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    {isExpanded ? <ChevronDown size={14} className="text-muted" /> : <ChevronRight size={14} className="text-muted" />}
                    <MapPin size={14} className="text-primary" />
                    <span className="text-sm font-semibold text-white">Zone {zone}</span>
                    <span className="text-xs text-muted">{customers.length} customers</span>
                    {overdueCount > 0 && (
                      <span className="badge badge-danger text-[10px]">{overdueCount} overdue</span>
                    )}
                  </div>
                  <div className="flex items-center gap-4 text-xs text-muted">
                    <span>{formatCurrency(customers.reduce((s, c) => s + c.totalRevenue, 0))} total</span>
                  </div>
                </button>

                {isExpanded && (
                  <table className="w-full">
                    <thead>
                      <tr className="border-t border-dark-border">
                        <th className="th">Customer</th>
                        <th className="th">City</th>
                        <th className="th text-center">
                          <span className="inline-flex items-center gap-1">Score <ScoreInfoTooltip /></span>
                        </th>
                        <th className="th">Status</th>
                        <th className="th text-center">Days Since Visit</th>
                        <th className="th text-center">Last Qty</th>
                        <th className="th">Predicted Next</th>
                        <th className="th text-right">Revenue</th>
                      </tr>
                    </thead>
                    <tbody>
                      {customers.map(c => (
                        <tr key={c.customerId} className="tr">
                          <td className="td">
                            <span className="font-semibold text-white text-xs">{c.customerName}</span>
                          </td>
                          <td className="td text-muted text-xs">{c.city || '—'}</td>
                          <td className="td"><UrgencyBar score={c.urgencyScore} /></td>
                          <td className="td"><StatusBadge status={c.urgencyLevel} /></td>
                          <td className="td text-center">
                            <span className={`font-semibold ${c.daysSinceLastVisit > 30 ? 'text-danger' : c.daysSinceLastVisit > 14 ? 'text-warning' : 'text-white'}`}>
                              {c.daysSinceLastVisit}d
                            </span>
                          </td>
                          <td className="td text-center text-muted">{c.lastInvoiceQty}</td>
                          <td className="td text-xs text-muted">{formatDate(c.predictedNextDate)}</td>
                          <td className="td text-right text-muted text-xs">{formatCurrency(c.totalRevenue)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            );
          })}

          {filteredScores.length === 0 && (
            <div className="card">
              <EmptyState
                icon={Users}
                title="No customers match filters"
                description="Try adjusting your zone or urgency filters"
              />
            </div>
          )}
        </>
      )}

      {/* ── Batch Tab ──────────────────────────────────────────── */}
      {tab === 'batch' && (
        <>
          {!batch ? (
            <div className="card">
              <EmptyState
                icon={Send}
                title="No dispatch batch loaded"
                description="Generate a new dispatch or select a recent batch from the Overview tab"
                action={
                  <button onClick={handleGenerate} disabled={generating} className="btn-primary text-xs">
                    <Send size={13} />
                    {generating ? 'Generating...' : 'Generate Dispatch'}
                  </button>
                }
              />
            </div>
          ) : (
            <>
              {/* Batch Header */}
              <div className="card p-5">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="flex items-center gap-3">
                      <h2 className="text-base font-bold text-white">{batch.name}</h2>
                      <StatusBadge status={batch.status} />
                    </div>
                    <p className="text-xs text-muted mt-1">
                      {batch.items.filter(i => i.selected).length} selected of {batch.items.length} total stops
                      {' · '}{batch.totalDrivers} drivers assigned
                      {' · '}Dispatch for {formatDate(batch.dispatchDate)}
                    </p>
                  </div>
                  {batch.status === 'DRAFT' && (
                    <div className="flex items-center gap-2">
                      <button onClick={handleCancel} className="btn-ghost text-xs text-danger hover:bg-danger/10">
                        <X size={13} /> Cancel
                      </button>
                      <button
                        onClick={handleApprove}
                        disabled={approving}
                        className="btn-primary text-xs"
                      >
                        <CheckCircle size={13} />
                        {approving ? 'Approving...' : 'Approve & Dispatch'}
                      </button>
                    </div>
                  )}
                  {batch.status === 'DISPATCHED' && (
                    <div className="flex items-center gap-2 text-success">
                      <CheckCircle size={16} />
                      <span className="text-sm font-semibold">Routes created and sent to drivers</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Driver-first zone view: pick a driver at the top, their zones
                  auto-select below, then pick customers zone-by-zone. */}
              <DispatchDriverView
                batch={batch}
                drivers={summary?.drivers || []}
                allZones={[...new Set([...allZones, ...Object.keys(summary?.zones || {})])].sort()}
                affinity={affinity}
                onAssign={handleAssignDriver}
                onExclude={handleExcludeItem}
                onInclude={handleIncludeItem}
                onAddZoneToDriver={async (driverId, zone) => {
                  const d = summary?.drivers.find(x => x.id === driverId);
                  if (!d) return;
                  const zones = [...d.zones, { zone, isPrimary: d.zones.length === 0 }];
                  await api.assignDriverZones(driverId, zones);
                  await loadOverview();
                }}
                onRemoveZoneFromDriver={async (driverId, zone) => {
                  const d = summary?.drivers.find(x => x.id === driverId);
                  if (!d) return;
                  const remaining = d.zones.filter(z => z.zone !== zone);
                  // Ensure at least one primary if any remain
                  if (remaining.length > 0 && !remaining.some(z => z.isPrimary)) {
                    remaining[0].isPrimary = true;
                  }
                  await api.assignDriverZones(driverId, remaining);
                  await loadOverview();
                }}
              />
            </>
          )}
        </>
      )}

    </div>
  );
}
